-- ===========================================================================
-- RailPrioritize — COMPLETE DATABASE SETUP
--
-- Generated by combining, in dependency order:
--   1. supabase/migrations/00_reset_auth.sql   (auth + profiles)
--   2. database/source-systems-schema.sql      (5 source-system tables)
--   3. block_schedules + dept_type enum        (optimiser output; required by
--                                               app/api/optimize-schedule)
--
-- HOW TO RUN
--   Supabase dashboard -> SQL Editor -> New query -> paste all -> Run.
--
-- Safe to re-run: every statement is guarded or idempotent, EXCEPT the two
-- DROP TABLE lines in section 1, which intentionally destroy public.users and
-- public.profiles. Existing profile rows are rebuilt by the backfill in 1.5.
-- ===========================================================================


-- ###########################################################################
-- SECTION 1 — AUTHENTICATION  (from supabase/migrations/00_reset_auth.sql)
-- ###########################################################################

-- ===========================================================================
-- 00_reset_auth.sql — Purge and rebuild the authentication schema.
--
-- Run in the Supabase SQL Editor. Destructive: see the DROP block below.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1. Wipe existing corrupt tables
--
-- CASCADE also drops dependent views, constraints and policies. Nothing else
-- in this project references public.users or public.profiles, but if you have
-- added your own objects on top of them, check before running.
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- ---------------------------------------------------------------------------
-- 2. Rebuild user profiles
-- ---------------------------------------------------------------------------
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL UNIQUE,
  department TEXT NOT NULL CHECK (department IN ('Engineering', 'S&T', 'Traction', 'Operations', 'Admin')),
  full_name TEXT,
  role TEXT DEFAULT 'USER',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- 3. Row Level Security
-- ---------------------------------------------------------------------------
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- ⚠ SECURITY WARNING -------------------------------------------------------
-- `WITH CHECK (true)` lets ANY caller holding the public anon key insert ANY
-- row into public.profiles — including an arbitrary `id` and `role = 'ADMIN'`.
-- It is kept here because it is what the spec asked for, and because a
-- client-side signup insert cannot work without it.
--
-- The trigger in section 4 makes that client-side insert unnecessary, so you
-- can close the hole by running the HARDENING block in section 5.
-- ---------------------------------------------------------------------------
CREATE POLICY "Allow public signup profile insertion"
ON public.profiles FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow users to view own profile"
ON public.profiles FOR SELECT USING (auth.uid() = id);

-- Not in the original spec, but without it a signed-in user cannot correct
-- their own name or department.
CREATE POLICY "Allow users to update own profile"
ON public.profiles FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- ---------------------------------------------------------------------------
-- 4. Auto-create a profile whenever an auth user is created
--
-- SECURITY DEFINER means this runs as the function owner and bypasses RLS, so
-- signup works without granting the anon role write access. Values come from
-- the `options.data` payload the login page sends to supabase.auth.signUp().
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, department, full_name, role)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data ->> 'department', 'Operations'),
    NEW.raw_user_meta_data ->> 'full_name',
    COALESCE(NEW.raw_user_meta_data ->> 'role', 'USER')
  )
  ON CONFLICT (id) DO NOTHING;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ---------------------------------------------------------------------------
-- 5. Backfill profiles for users who already exist
--
-- The trigger above only fires on NEW auth.users rows. Anyone who signed up
-- before this migration ran (or before the profiles table was dropped) would
-- otherwise be left with an account that has no profile, and the dashboard
-- would hang on "Loading your profile…".
-- ---------------------------------------------------------------------------
INSERT INTO public.profiles (id, email, department, full_name, role)
SELECT
  u.id,
  u.email,
  COALESCE(u.raw_user_meta_data ->> 'department', 'Operations'),
  COALESCE(u.raw_user_meta_data ->> 'full_name', split_part(u.email, '@', 1)),
  COALESCE(u.raw_user_meta_data ->> 'role', 'USER')
FROM auth.users u
WHERE u.email IS NOT NULL
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 6. HARDENING (optional — recommended before any real deployment)
--
-- Uncomment to replace the permissive insert policy with one that only lets a
-- signed-in user create their OWN profile row. Safe to apply because the
-- trigger above already creates profiles during signup.
-- ---------------------------------------------------------------------------
-- DROP POLICY IF EXISTS "Allow public signup profile insertion" ON public.profiles;
-- CREATE POLICY "Users may insert only their own profile"
-- ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);


-- ###########################################################################
-- SECTION 2 — SOURCE SYSTEMS  (from database/source-systems-schema.sql)
-- ###########################################################################

-- ===========================================================================
-- Source-system ingestion tables.
--
-- Each maintenance system owns its own table so raw feeds stay separable and
-- auditable. lib/data-sources.ts unifies them for the optimiser.
--
-- Run in the Supabase SQL Editor. Safe to re-run.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- Engineering — Track Management System
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tms_defects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_id VARCHAR(50) NOT NULL UNIQUE,
    section_code VARCHAR(50) NOT NULL,
    defect_description TEXT NOT NULL DEFAULT '',
    risk_score NUMERIC(5,2) NOT NULL DEFAULT 50,
    duration_required_hrs NUMERIC(5,2) NOT NULL DEFAULT 2,
    asset_criticality_score INT NOT NULL DEFAULT 5,
    is_overdue BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Signalling & Telecom — Signal Maintenance Management System
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS smms_defects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_id VARCHAR(50) NOT NULL UNIQUE,
    section_code VARCHAR(50) NOT NULL,
    defect_description TEXT NOT NULL DEFAULT '',
    risk_score NUMERIC(5,2) NOT NULL DEFAULT 50,
    duration_required_hrs NUMERIC(5,2) NOT NULL DEFAULT 2,
    asset_criticality_score INT NOT NULL DEFAULT 5,
    is_overdue BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Traction / TRD — Traction Distribution Management System
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tdms_defects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_id VARCHAR(50) NOT NULL UNIQUE,
    section_code VARCHAR(50) NOT NULL,
    defect_description TEXT NOT NULL DEFAULT '',
    risk_score NUMERIC(5,2) NOT NULL DEFAULT 50,
    duration_required_hrs NUMERIC(5,2) NOT NULL DEFAULT 2,
    asset_criticality_score INT NOT NULL DEFAULT 5,
    is_overdue BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Block Demand Management System — the block requests departments file today
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS bdms_demands (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    demand_id VARCHAR(50) NOT NULL UNIQUE,
    department VARCHAR(30) NOT NULL,
    section_code VARCHAR(50) NOT NULL,
    requested_start TIMESTAMPTZ,
    requested_end TIMESTAMPTZ,
    duration_required_hrs NUMERIC(5,2) NOT NULL DEFAULT 2,
    purpose TEXT NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL DEFAULT 'Pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Corridor Availability — traffic-free slots published by operations
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS coa_slots (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    section_code VARCHAR(50) NOT NULL,
    slot_start TIMESTAMPTZ NOT NULL,
    slot_end TIMESTAMPTZ NOT NULL,
    freight_impact_score INT NOT NULL DEFAULT 3,
    passenger_traffic_density VARCHAR(20) NOT NULL DEFAULT 'Medium',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS coa_slots_slot_key
    ON coa_slots (section_code, slot_start);

CREATE INDEX IF NOT EXISTS tms_defects_section_idx  ON tms_defects  (section_code);
CREATE INDEX IF NOT EXISTS smms_defects_section_idx ON smms_defects (section_code);
CREATE INDEX IF NOT EXISTS tdms_defects_section_idx ON tdms_defects (section_code);
CREATE INDEX IF NOT EXISTS bdms_demands_section_idx ON bdms_demands (section_code);

-- ---------------------------------------------------------------------------
-- Row Level Security
--
-- Demo-grade: permissive so the anon key can read, and so the ingestion route
-- can write with the anon key when no service-role key is configured.
-- Tighten before any real deployment.
-- ---------------------------------------------------------------------------
DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['tms_defects','smms_defects','tdms_defects','bdms_demands','coa_slots']
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('DROP POLICY IF EXISTS demo_all_%I ON public.%I', t, t);
    EXECUTE format(
      'CREATE POLICY demo_all_%I ON public.%I FOR ALL USING (true) WITH CHECK (true)',
      t, t
    );
  END LOOP;
END$$;


-- ###########################################################################
-- SECTION 3 — OPTIMISER OUTPUT
--
-- block_schedules stores what the AI recommends. It is NOT in either source
-- file, but app/api/optimize-schedule/route.ts writes to it, so a setup
-- without it would fail on every persist.
--
-- The superseded maintenance_defects / corridor_windows tables are
-- deliberately omitted: since the source-system refactor, no application code
-- reads them.
-- ###########################################################################

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'dept_type') THEN
    CREATE TYPE dept_type AS ENUM ('Engineering', 'S&T', 'Traction_TRD');
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS block_schedules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    section_code VARCHAR(50) NOT NULL,
    block_start TIMESTAMPTZ NOT NULL,
    block_end TIMESTAMPTZ NOT NULL,
    combined_departments dept_type[] NOT NULL,
    assigned_defect_ids UUID[] NOT NULL,
    total_downtime_saved_hrs NUMERIC(6,2) NOT NULL,
    status VARCHAR(20) DEFAULT 'Recommended',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS block_schedules_section_idx
    ON block_schedules (section_code, block_start);

ALTER TABLE block_schedules ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS demo_all_block_schedules ON block_schedules;
CREATE POLICY demo_all_block_schedules ON block_schedules
    FOR ALL USING (true) WITH CHECK (true);


-- ===========================================================================
-- DONE.
--
-- Verify with:
--   SELECT table_name FROM information_schema.tables
--   WHERE table_schema = 'public' ORDER BY table_name;
--
-- Expected: bdms_demands, block_schedules, coa_slots, profiles,
--           smms_defects, tdms_defects, tms_defects
-- ===========================================================================
